import localFont from "next/font/local";
import "./globals.css";
import NavBar from "./components/navbar/NavBar";
import Footer from "./components/footer/Footer";
import AppProvider from "../app/providers/AppProvider";
import { MantineProvider } from "@mantine/core";
import { ModalsProvider } from "@mantine/modals";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <AppProvider>
          <MantineProvider>
            <ModalsProvider>
              <div className="container">
                <NavBar />
                {children}
                <Footer />
              </div>
            </ModalsProvider>
          </MantineProvider>
        </AppProvider>
      </body>
    </html>
  );
}
